name: Points
main: balckangel.Points.Points
version: 2.0
commands:
  p:
    description: Permet de gerer les points (generaux et missions)
    usage: /p [reload|on|off|start|stop|pts|high|highcc|all|go|but]