name: OreDetector
main: balckangel.OreDetector.OreDetector
version: 1.2
commands:
  od:
    description: Permet au joueur de localiser le bloc specifie le plus proche
    usage: /od [reload|on|off|nom_bloc] [rayon] [hauteur_dessus] [hauteur_dessous]