name: PrivateProperty
main: balckangel.PrivateProperty.PrivateProperty
version: 1.3
commands:
  pp:
    description: Permet la gestion de coffre, de four et d'alambic personnel
    usage: /pp [reload|on|off|set]